package com.anon.backend.entity;

import java.io.Serial;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import java.io.Serializable;
import java.time.LocalDateTime;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

/**
* when registering, user must provide its session id. Once session validation passed, use session id to generate a pair of keys
*
* @author anon
* @since 2025-01-18
*/
@Getter
@Setter
@Accessors(chain = true)
@Schema(name = "User", description = "when registering, user must provide its session id. Once session validation passed, use session id to generate a pair of keys")
public class User implements Serializable {
  @Serial
  private static final long serialVersionUID = 1L;

  @TableId(value = "id", type = IdType.AUTO)
  private Long id;

  private String username;

  @Schema(description = "encrypted by bcrypt, salting, 60")
  private String password;

  private String school;

  private String phone;

  @Schema(description = "generated by RSA, base64 encoded")
  private String pubKey;

  @TableLogic
  private Boolean isDelete;

  private LocalDateTime createAt;

  private LocalDateTime updateAt;

  private LocalDateTime hideUntil;
}
