db:
  driver: com.mysql.cj.jdbc.Driver
  domain: localhost:3306/forum?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  url: jdbc:mysql://${db.domain}
  username: root
  password: password

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${db.domain}
    username: ${db.username}
    password: ${db.password}
  rabbitmq:
    addresses: localhost
    virtual-host: /dev
server:
  port: 8080
  address: localhost
  ssl:
    enabled: false


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
decorator:
  datasource:
    p6spy:
      custom-appender-class: com.p6spy.engine.spy.appender.Slf4JLogger
