spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: ${meta.package-name}.controller

---
meta:
  user: anon
  package-name: com.anon.backend
  mapper-scan: ${meta.package-name}.mapper

spring:
  application:
    name: backend
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml