spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: ${meta.package-name}.controller

---
meta:
  user: anon
  package-name: com.anon.backend
  mapper-scan: ${meta.package-name}.mapper

spring:
  application:
    name: backend
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml

---
# dev env
db:
  driver: com.mysql.cj.jdbc.Driver
  domain: localhost:3306/forum?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  url: jdbc:mysql://${db.domain}
  username: root
  password: 030212Lyx

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${db.domain}
    username: ${db.username}
    password: ${db.password}
server:
  port: 8080
  address: localhost
  ssl:
    enabled: false


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
decorator:
  datasource:
    p6spy:
      custom-appender-class: com.p6spy.engine.spy.appender.Slf4JLogger

---
# prod env
db:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/forum?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: 030212Lyx

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: ${db.driver}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
server:
  port: 8080
  address: localhost
  ssl:
    enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false